channels:
  - conda-forge

dependencies:
  - python=3.10.12
  - pip=23.2.1
  - robocorp-truststore=0.8.0
  - pip:
    - python-dateutil==2.9.0.post0 
    - rpaframework==28.6.1
    - robocorp==2.1.0
    - robocorp-browser==2.3.3
    - requests==2.32.3

